### ISSUE TITLE
Regex is not matching for [UnauthorizedError] error scenario 

### ISSUE THREAD

**Issue by keshav143420** [vamship/cdk-utils#6]
Regex is not matching for "[UnauthorizedError] \<some message\>" message but it does work for [ForbiddenError] \<some message\>" scenario

https://github.com/vamship/cdk-utils/blob/aab4ffef581bc03cb6914d35bedbfa98d3a2007b/src/api/http-method-factory.ts#L427

**Comment by vamship** [comment]
Closed
